### ISSUE TITLE
Styling & Animation - Dark Theme & Accents

### ISSUE THREAD

**Issue by tmanundercover** [tmanundercover/The-Handsomest-Nerd-Playground#251]
Create a dark theme with vibrant accent colors.

Implement shadow and UI component styling.

Ensure accessibility compliance.

Example CSS:
```css
.dark-mode { background-color: #121212; color: #fff; }
```
